title:        Blog
tagline:      "Erthalion\'s blog"
description:  "My thoughts and experiments."
url:          http://erthalion.info
version:      0.0.1
author:
  name:       ''
  email:      ''
markdown:     rdiscount
permalink:    pretty
pygments:     true
paginate:     2
paginate_path: "blog/page:num"
comments:
    provider: disqus
    disqus:
        short_name: erthalion
